[package]
name = "ddoresolver-rs"
version = "0.1.0"
documentation = "https://docs.rs/ddoresolver-rs"
description = "function to resolve did document from url"
license = "Apache-2.0"
repository = "https://github.com/jolocom/ddoresolver-rs"
readme = "README.md"
authors = ["Ivan Temchenko <35359595i@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
did-key = "0.0.8"
regex = "1"
